### ISSUE TITLE
Can't join worlds when using newer versions of java(11+)

### ISSUE THREAD

**Issue by ghost** [Johni0702/fade-in-chunks#9] opened 2021-04-09 15:20 UTC
The minecraft client launches, but when I select a world or generate a new one the process goes until joining the world then saves it and crashes

[crash-2021-04-09_16.20.17-client.txt](https://github.com/Johni0702/fade-in-chunks/files/6286741/crash-2021-04-09_16.20.17-client.txt) with java 11

**Note**:Tested with AdoptJDK

**Comment by Johni0702** [comment] 2021-04-09 15:26
I don't see how this has anything to do with Java 11, did you even test Java 10 / older?

Duplicate of #8

**Closed as completed by Johni0702** 2021-04-09 15:26 UTC

**Comment by ghost** [comment] 2021-04-09 15:27
the bundled java and Adopt JDK8 works fine, I'll test with 9-10

**Comment by ghost** [comment] 2021-04-09 15:42
> 
> 
> I don't see how this has anything to do with Java 11, did you even test Java 10 / older?
> 
> Duplicate of #8

After testing more carefully a sodium rev did managed to get in(so that was the actual problem), but eventually it led me to discover a possible incompatibilty with the mod "indium"
[crash-2021-04-09_17.06.24-client.txt](https://github.com/Johni0702/fade-in-chunks/files/6287101/crash-2021-04-09_17.06.24-client.txt)
