### ISSUE TITLE
Far away chunks don't have an animation

### ISSUE THREAD

**Issue by CalXee** [Johni0702/fade-in-chunks#7] opened 2021-03-10 19:56 UTC
Chunks loading in far away appears like vanilla without the animation.

https://user-images.githubusercontent.com/68349758/110689562-d1dbc400-81b0-11eb-8fd3-80c96f022cd9.mp4

**Comment by Johni0702** [comment] 2021-03-11 00:24
Quick explanation of how the mod works:

> The way Fade In Chunks does its fading is to not actually change the chunks' opacity (cause that's complicated with caves and transparent blocks and such) but to instead interpolate each pixel between its normal color and the background color (I believe that's how bedrock does it as well).
The easy way to do this is to assume that background color is the same thing as fog color, which is true in most cases. and in those were it isn't, vanilla already has what I would consider a graphics bug in that you can clearly make out the edge of foggy mountains when really the point of the fog was to fade them into the background. so, if one were to fix this via a mod, having it as its own dedicated mod would be valuable and it would also fix the fade in effect, meaning just assuming background color = fog color isn't too bad of an assumption.

So they do have an animation but it's fading from foggy to foggy. This is just an unfortunate shortcoming of how the whole thing is implemented.
Fixing this would effectively yield aforementioned fog-fix mod and that is something I'd like to do eventually but as explained it'll be its own mod, so I'm closing this issue as "working as intended" (or "vanilla bug" if you will).

**Closed as completed by Johni0702** 2021-03-11 00:24 UTC
Labels: bug, wontfix

**Comment by CalXee** [comment] 2021-03-11 01:11
Coolio, thanks for the explanation! :)
